### ISSUE TITLE
Trying to change a channel category gives an error

### ISSUE THREAD

**Issue by ronaldmiranda** [Lucky3028/terraform-provider-discord#67] opened 2023-02-04 22:21 UTC
when you try to change a channel category, it gives an return from cloudflare giving an 400 error

**Comment by Lucky3028** [comment] 2023-03-03 09:39
This error was not reproduced here. Is it still occurring? @ronaldmiranda

**Comment by Lucky3028** [comment] 2024-04-13 13:52
@ronaldmiranda 
Since you have not responded, I am closing this issue. If you have any questions, please feel free to comment.

**Closed by Lucky3028** 2024-04-13 13:52 UTC
Labels: bug
